# Site settings
title: iOSDevelopTeam's Blog
SEOTitle: iOS开发小分队技术分享团队博客 | iOSDevelopTeam's Blog
header-img: img/post-bg-desk.jpg
email: shavekevin@gmail.com
description: "iOS开发小分队技术分享团队博客."
keyword: "iOSDevelopTeam, iOSDevelopTeam's Blog, iOS开发小分队技术分享团队的博客, iOS开发小分队, 秦小风, iOS, Apple, iPhone"
url: "http://iOSDevelopTeam.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/iOSDevelopTeam/iOSDevelopTeam.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "热爱生活，分享快乐。好记性不如烂笔头。多写，多记，多实践，多思考。"
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`你的大头贴，请使用绝对地址.注意：名字区分大小写！后缀名也是



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     shavekevin
github_username:    iOSDevelopTeam
facebook_username:  shavekevin
jianshu_username:   485819d6ff79
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 01d3703a6026268e5057                            #生成的clientID
  clientSecret: 2a6ec6b0ffdd2c71a84852d53799e8d6d20fe745    #生成的clientSecret
  repo: iOSDevelopTeam.github.io    #仓库名称
  owner: iOSDevelopTeam    #github用户名
  admin: iOSDevelopTeam
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 3a85cee99d281f2861b9aecd58817b93

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: iOSDevelopTeam.auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
友情链接: [
    {
        title: "秦小风的博客",
        href: "http://www.shavekevin.com"
    },{
        title: "简书·BeyoundCong",
        href: "https://www.jianshu.com/u/81061b93579b"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }


]
